//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgsEcfControls.Properties.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background worker task identified a problem.
        /// </summary>
        internal static string BackgrounfWorker_Failed {
            get {
                return ResourceManager.GetString("BackgrounfWorker_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change all.
        /// </summary>
        internal static string FilterSelector_ChangeAll {
            get {
                return ResourceManager.GetString("FilterSelector_ChangeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string FilterSelector_Of {
            get {
                return ResourceManager.GetString("FilterSelector_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string ParameterView_GroupSeperator {
            get {
                return ResourceManager.GetString("ParameterView_GroupSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ParameterView_ValueSeperator {
            get {
                return ResourceManager.GetString("ParameterView_ValueSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies the filter to views.
        /// </summary>
        internal static string ToolTip_FilterApplyButton {
            get {
                return ResourceManager.GetString("ToolTip_FilterApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the filter and refreshes the views.
        /// </summary>
        internal static string ToolTip_FilterClearButton {
            get {
                return ResourceManager.GetString("ToolTip_FilterClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of parameters shown at once.
        /// </summary>
        internal static string ToolTip_ParameterCountSelector {
            get {
                return ResourceManager.GetString("ToolTip_ParameterCountSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of parameters shown.
        /// </summary>
        internal static string ToolTip_ParameterGroupSelector {
            get {
                return ResourceManager.GetString("ToolTip_ParameterGroupSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textual parameter search filter on values (Case sensitive Like).
        /// </summary>
        internal static string ToolTip_ParameterLikeInput {
            get {
                return ResourceManager.GetString("ToolTip_ParameterLikeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the visible parameter items.
        /// </summary>
        internal static string ToolTip_ParameterSelector {
            get {
                return ResourceManager.GetString("ToolTip_ParameterSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets alphabetical sorting order for parameter names.
        /// </summary>
        internal static string ToolTip_ParameterSorterAlphabeticOrder {
            get {
                return ResourceManager.GetString("ToolTip_ParameterSorterAlphabeticOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the sorting direction.
        /// </summary>
        internal static string ToolTip_ParameterSorterDirection {
            get {
                return ResourceManager.GetString("ToolTip_ParameterSorterDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets hierarchical sorting order.
        /// </summary>
        internal static string ToolTip_ParameterSorterOriginOrder {
            get {
                return ResourceManager.GetString("ToolTip_ParameterSorterOriginOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Parameters are inherited to the selected tree element.
        /// </summary>
        internal static string ToolTip_ParameterView_InheritedColumn {
            get {
                return ResourceManager.GetString("ToolTip_ParameterView_InheritedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Parameters overwriting an inherited parameter.
        /// </summary>
        internal static string ToolTip_ParameterView_OverwritingColumn {
            get {
                return ResourceManager.GetString("ToolTip_ParameterView_OverwritingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the visible tree item attributes.
        /// </summary>
        internal static string ToolTip_TreeAttributeSelector {
            get {
                return ResourceManager.GetString("ToolTip_TreeAttributeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of tree items shown at once.
        /// </summary>
        internal static string ToolTip_TreeItemCountSelector {
            get {
                return ResourceManager.GetString("ToolTip_TreeItemCountSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of tree items shown.
        /// </summary>
        internal static string ToolTip_TreeItemGroupSelector {
            get {
                return ResourceManager.GetString("ToolTip_TreeItemGroupSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the visible tree item types.
        /// </summary>
        internal static string ToolTip_TreeItemTypeSelector {
            get {
                return ResourceManager.GetString("ToolTip_TreeItemTypeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textual tree item search filter on display node name (Case sensitive Like).
        /// </summary>
        internal static string ToolTip_TreeLikeInput {
            get {
                return ResourceManager.GetString("ToolTip_TreeLikeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets alphabetical sorting order for element names.
        /// </summary>
        internal static string ToolTip_TreeSorterAlphabeticOrder {
            get {
                return ResourceManager.GetString("ToolTip_TreeSorterAlphabeticOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the sorting direction.
        /// </summary>
        internal static string ToolTip_TreeSorterDirection {
            get {
                return ResourceManager.GetString("ToolTip_TreeSorterDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets original sorting order (from File).
        /// </summary>
        internal static string ToolTip_TreeSorterOriginOrder {
            get {
                return ResourceManager.GetString("ToolTip_TreeSorterOriginOrder", resourceCulture);
            }
        }
    }
}
