//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgsEcfControls.Properties.titles", typeof(titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has value.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_ColumnHeaderHasValue {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_ColumnHeaderHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is force escaped.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_ColumnHeaderIsForceEscaped {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_ColumnHeaderIsForceEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare file.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_CompareFile {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_CompareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition file.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_DefinitionFile {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_DefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecated definitions.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_Header {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        internal static string EcfFileDialog_CreateFileDialog {
            get {
                return ResourceManager.GetString("EcfFileDialog_CreateFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfile.
        /// </summary>
        internal static string EcfFileDialog_CreateFileName {
            get {
                return ResourceManager.GetString("EcfFileDialog_CreateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File encoding.
        /// </summary>
        internal static string EcfFileOpenDialog_EncodingBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_EncodingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path and name.
        /// </summary>
        internal static string EcfFileOpenDialog_FilePathAndNameBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_FilePathAndNameBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find file.
        /// </summary>
        internal static string EcfFileOpenDialog_FindFileDialog {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_FindFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format definition.
        /// </summary>
        internal static string EcfFileOpenDialog_FormatDefinitionBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_FormatDefinitionBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define new file.
        /// </summary>
        internal static string EcfFileOpenDialog_NewFileDialog {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_NewFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line symbol.
        /// </summary>
        internal static string EcfFileOpenDialog_NewLineSymbolBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_NewLineSymbolBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing file.
        /// </summary>
        internal static string EcfFileOpenDialog_OpenFileDialog {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_OpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddChildBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddChildBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddComment {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddParameter {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add root block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddRootBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddRootBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit child block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditChildBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditChildBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditComment {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameter item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditParameter {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit root block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditRootBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditRootBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the item type to be added.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_SelectItem {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values / Groups.
        /// </summary>
        internal static string EcfItemEditingDialog_ParameterItem_ValuesLabel {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ParameterItem_ValuesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing error.
        /// </summary>
        internal static string ErrorView_EditingError {
            get {
                return ResourceManager.GetString("ErrorView_EditingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing errors.
        /// </summary>
        internal static string ErrorView_EditingErrors {
            get {
                return ResourceManager.GetString("ErrorView_EditingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error group.
        /// </summary>
        internal static string ErrorView_ErrorGroupColumn {
            get {
                return ResourceManager.GetString("ErrorView_ErrorGroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ErrorView_ErrorNumberColumn {
            get {
                return ResourceManager.GetString("ErrorView_ErrorNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content errors.
        /// </summary>
        internal static string ErrorView_Header {
            get {
                return ResourceManager.GetString("ErrorView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing error.
        /// </summary>
        internal static string ErrorView_ParsingError {
            get {
                return ResourceManager.GetString("ErrorView_ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing errors.
        /// </summary>
        internal static string ErrorView_ParsingErrors {
            get {
                return ResourceManager.GetString("ErrorView_ParsingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in editor.
        /// </summary>
        internal static string ErrorView_ShowInEditor {
            get {
                return ResourceManager.GetString("ErrorView_ShowInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in file.
        /// </summary>
        internal static string ErrorView_ShowInFile {
            get {
                return ResourceManager.GetString("ErrorView_ShowInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Generic_Abort {
            get {
                return ResourceManager.GetString("Generic_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Generic_Active {
            get {
                return ResourceManager.GetString("Generic_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add after.
        /// </summary>
        internal static string Generic_AddAfter {
            get {
                return ResourceManager.GetString("Generic_AddAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to.
        /// </summary>
        internal static string Generic_AddTo {
            get {
                return ResourceManager.GetString("Generic_AddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Generic_Attention {
            get {
                return ResourceManager.GetString("Generic_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Generic_Attribute {
            get {
                return ResourceManager.GetString("Generic_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Generic_Attributes {
            get {
                return ResourceManager.GetString("Generic_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Generic_BackButton {
            get {
                return ResourceManager.GetString("Generic_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Generic_Change {
            get {
                return ResourceManager.GetString("Generic_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child item.
        /// </summary>
        internal static string Generic_ChildElement {
            get {
                return ResourceManager.GetString("Generic_ChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child items.
        /// </summary>
        internal static string Generic_ChildElements {
            get {
                return ResourceManager.GetString("Generic_ChildElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Generic_Comment {
            get {
                return ResourceManager.GetString("Generic_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Generic_Comments {
            get {
                return ResourceManager.GetString("Generic_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Generic_Copy {
            get {
                return ResourceManager.GetString("Generic_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item.
        /// </summary>
        internal static string Generic_DataElement {
            get {
                return ResourceManager.GetString("Generic_DataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data items.
        /// </summary>
        internal static string Generic_DataElements {
            get {
                return ResourceManager.GetString("Generic_DataElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type.
        /// </summary>
        internal static string Generic_DataType {
            get {
                return ResourceManager.GetString("Generic_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string Generic_Definitions {
            get {
                return ResourceManager.GetString("Generic_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Generic_Element {
            get {
                return ResourceManager.GetString("Generic_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Generic_Elements {
            get {
                return ResourceManager.GetString("Generic_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Generic_Errors {
            get {
                return ResourceManager.GetString("Generic_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Generic_Group {
            get {
                return ResourceManager.GetString("Generic_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Generic_Info {
            get {
                return ResourceManager.GetString("Generic_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        internal static string Generic_Inherited {
            get {
                return ResourceManager.GetString("Generic_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is optional.
        /// </summary>
        internal static string Generic_IsOptional {
            get {
                return ResourceManager.GetString("Generic_IsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string Generic_LineNumber {
            get {
                return ResourceManager.GetString("Generic_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Generic_Name {
            get {
                return ResourceManager.GetString("Generic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string Generic_Names {
            get {
                return ResourceManager.GetString("Generic_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Generic_Parameter {
            get {
                return ResourceManager.GetString("Generic_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Generic_Parameters {
            get {
                return ResourceManager.GetString("Generic_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste after.
        /// </summary>
        internal static string Generic_PasteAfter {
            get {
                return ResourceManager.GetString("Generic_PasteAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste to.
        /// </summary>
        internal static string Generic_PasteTo {
            get {
                return ResourceManager.GetString("Generic_PasteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick item.
        /// </summary>
        internal static string Generic_PickItem {
            get {
                return ResourceManager.GetString("Generic_PickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post mark.
        /// </summary>
        internal static string Generic_PostMark {
            get {
                return ResourceManager.GetString("Generic_PostMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre mark.
        /// </summary>
        internal static string Generic_PreMark {
            get {
                return ResourceManager.GetString("Generic_PreMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Generic_Properties {
            get {
                return ResourceManager.GetString("Generic_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Generic_Remove {
            get {
                return ResourceManager.GetString("Generic_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string Generic_Replacement_Empty {
            get {
                return ResourceManager.GetString("Generic_Replacement_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Generic_Reset {
            get {
                return ResourceManager.GetString("Generic_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root item.
        /// </summary>
        internal static string Generic_RootElement {
            get {
                return ResourceManager.GetString("Generic_RootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root items.
        /// </summary>
        internal static string Generic_RootElements {
            get {
                return ResourceManager.GetString("Generic_RootElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Generic_Search {
            get {
                return ResourceManager.GetString("Generic_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Generic_Type {
            get {
                return ResourceManager.GetString("Generic_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Generic_Value {
            get {
                return ResourceManager.GetString("Generic_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string Generic_Values {
            get {
                return ResourceManager.GetString("Generic_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element data.
        /// </summary>
        internal static string InfoView_ElementData {
            get {
                return ResourceManager.GetString("InfoView_ElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        internal static string InfoView_Header {
            get {
                return ResourceManager.GetString("InfoView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter data.
        /// </summary>
        internal static string InfoView_ParameterData {
            get {
                return ResourceManager.GetString("InfoView_ParameterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter view.
        /// </summary>
        internal static string ParameterView_Header {
            get {
                return ResourceManager.GetString("ParameterView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inherited.
        /// </summary>
        internal static string ParameterView_Header_InheritedParameters {
            get {
                return ResourceManager.GetString("ParameterView_Header_InheritedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwriting.
        /// </summary>
        internal static string ParameterView_Header_OverwritingParameters {
            get {
                return ResourceManager.GetString("ParameterView_Header_OverwritingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string ParameterView_ParameterNameColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ParameterView_ParameterNumberColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over..
        /// </summary>
        internal static string ParameterView_ParameterOverwritingColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterOverwritingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree element.
        /// </summary>
        internal static string ParameterView_ParameterParentColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterParentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        internal static string ParameterView_UnnamedParent {
            get {
                return ResourceManager.GetString("ParameterView_UnnamedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree items.
        /// </summary>
        internal static string TreeView_FilterSelector_Elements {
            get {
                return ResourceManager.GetString("TreeView_FilterSelector_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view.
        /// </summary>
        internal static string TreeView_Header {
            get {
                return ResourceManager.GetString("TreeView_Header", resourceCulture);
            }
        }
    }
}
