//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgsEcfControls.Properties.titles", typeof(titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content loading errors.
        /// </summary>
        internal static string ErrorView_Header {
            get {
                return ResourceManager.GetString("ErrorView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errors.
        /// </summary>
        internal static string ErrorView_Header_Errors {
            get {
                return ResourceManager.GetString("ErrorView_Header_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string GenericAttention {
            get {
                return ResourceManager.GetString("GenericAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        internal static string InfoView_AddData {
            get {
                return ResourceManager.GetString("InfoView_AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element attributes.
        /// </summary>
        internal static string InfoView_ElementAttributes {
            get {
                return ResourceManager.GetString("InfoView_ElementAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child block count.
        /// </summary>
        internal static string InfoView_ElementChildBlockCount {
            get {
                return ResourceManager.GetString("InfoView_ElementChildBlockCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child count.
        /// </summary>
        internal static string InfoView_ElementChildCount {
            get {
                return ResourceManager.GetString("InfoView_ElementChildCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element comment.
        /// </summary>
        internal static string InfoView_ElementComment {
            get {
                return ResourceManager.GetString("InfoView_ElementComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element pre sign.
        /// </summary>
        internal static string InfoView_ElementPreSign {
            get {
                return ResourceManager.GetString("InfoView_ElementPreSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type.
        /// </summary>
        internal static string InfoView_ElementType {
            get {
                return ResourceManager.GetString("InfoView_ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        internal static string InfoView_Header {
            get {
                return ResourceManager.GetString("InfoView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter attributes.
        /// </summary>
        internal static string InfoView_ParameterAttributes {
            get {
                return ResourceManager.GetString("InfoView_ParameterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter comment.
        /// </summary>
        internal static string InfoView_ParameterComment {
            get {
                return ResourceManager.GetString("InfoView_ParameterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string ParameterView_FilterSelector_Parameters {
            get {
                return ResourceManager.GetString("ParameterView_FilterSelector_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter view.
        /// </summary>
        internal static string ParameterView_Header {
            get {
                return ResourceManager.GetString("ParameterView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inherited.
        /// </summary>
        internal static string ParameterView_Header_InheritedParameters {
            get {
                return ResourceManager.GetString("ParameterView_Header_InheritedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string ParameterView_Header_OverallParameters {
            get {
                return ResourceManager.GetString("ParameterView_Header_OverallParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwriting.
        /// </summary>
        internal static string ParameterView_Header_OverwritingParameters {
            get {
                return ResourceManager.GetString("ParameterView_Header_OverwritingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string ParameterView_ParameterCommentColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterCommentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inher..
        /// </summary>
        internal static string ParameterView_ParameterInheritedColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterInheritedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string ParameterView_ParameterNameColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string ParameterView_ParameterNumberColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over..
        /// </summary>
        internal static string ParameterView_ParameterOverwritingColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterOverwritingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree element.
        /// </summary>
        internal static string ParameterView_ParameterParentColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterParentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ParameterView_ParameterValueColumn {
            get {
                return ResourceManager.GetString("ParameterView_ParameterValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        internal static string ParameterView_UnnamedParent {
            get {
                return ResourceManager.GetString("ParameterView_UnnamedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string ParameterView_ValueGroup {
            get {
                return ResourceManager.GetString("ParameterView_ValueGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string TreeView_CommentNodeName {
            get {
                return ResourceManager.GetString("TreeView_CommentNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree attributes.
        /// </summary>
        internal static string TreeView_FilterSelector_Attributes {
            get {
                return ResourceManager.GetString("TreeView_FilterSelector_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree items.
        /// </summary>
        internal static string TreeView_FilterSelector_Elements {
            get {
                return ResourceManager.GetString("TreeView_FilterSelector_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view.
        /// </summary>
        internal static string TreeView_Header {
            get {
                return ResourceManager.GetString("TreeView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root items.
        /// </summary>
        internal static string TreeView_Header_RootElements {
            get {
                return ResourceManager.GetString("TreeView_Header_RootElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub items.
        /// </summary>
        internal static string TreeView_Header_SubElements {
            get {
                return ResourceManager.GetString("TreeView_Header_SubElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string TreeView_SelectableElements_Comments {
            get {
                return ResourceManager.GetString("TreeView_SelectableElements_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data blocks.
        /// </summary>
        internal static string TreeView_SelectableElements_DataBlocks {
            get {
                return ResourceManager.GetString("TreeView_SelectableElements_DataBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed node.
        /// </summary>
        internal static string TreeView_UnnamedNodeName {
            get {
                return ResourceManager.GetString("TreeView_UnnamedNodeName", resourceCulture);
            }
        }
    }
}
