//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumRecources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumRecources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgsEcfEditorApp.Properties.EnumRecources", typeof(EnumRecources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string EcfFileViewTools_EcfStructureFilter_SelectableItems_Comments {
            get {
                return ResourceManager.GetString("EcfFileViewTools.EcfStructureFilter+SelectableItems.Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data blocks.
        /// </summary>
        internal static string EcfFileViewTools_EcfStructureFilter_SelectableItems_DataBlocks {
            get {
                return ResourceManager.GetString("EcfFileViewTools.EcfStructureFilter+SelectableItems.DataBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string EcfFileViewTools_EcfStructureFilter_SelectableItems_Parameters {
            get {
                return ResourceManager.GetString("EcfFileViewTools.EcfStructureFilter+SelectableItems.Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating error.
        /// </summary>
        internal static string EgsEcfParser_EcfErrorGroups_Creating {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrorGroups.Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing error.
        /// </summary>
        internal static string EgsEcfParser_EcfErrorGroups_Editing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrorGroups.Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation error.
        /// </summary>
        internal static string EgsEcfParser_EcfErrorGroups_Interpretation {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrorGroups.Interpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural error.
        /// </summary>
        internal static string EgsEcfParser_EcfErrorGroups_Structural {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrorGroups.Structural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute doubled.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_AttributeDoubled {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.AttributeDoubled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory attribute missing.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_AttributeMissing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute not defined.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_AttributeUnknown {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.AttributeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element structure closer without opener.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockCloserWithoutOpener {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockCloserWithoutOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element data type missing.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockDataTypeMissing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockDataTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element data type not defined.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockDataTypeUnknown {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockDataTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element id not unique.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockIdNotUnique {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element inheritor missing.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockInheritorMissing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockInheritorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data block not createable.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockNotCreateable {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockNotCreateable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element structure opener without closer.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockOpenerWithoutCloser {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockOpenerWithoutCloser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element post mark missing.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockPostMarkMissing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockPostMarkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element post mark not defined.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockPostMarkUnknown {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockPostMarkUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element pre mark missing.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockPreMarkMissing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockPreMarkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element pre mark not defined.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_BlockPreMarkUnknown {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.BlockPreMarkUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key null or empty.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_KeyNullOrEmpty {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.KeyNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter doubled.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ParameterDoubled {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ParameterDoubled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory parameter missing.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ParameterMissing {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not createable.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ParameterNotCreateable {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ParameterNotCreateable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not defined.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ParameterUnknown {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ParameterUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter without a parent element.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ParameterWithoutParent {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ParameterWithoutParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_Unknown {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains prohibited symbols.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ValueContainsProhibitedPhrases {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ValueContainsProhibitedPhrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is blank.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ValueEmpty {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value present.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ValueGroupEmpty {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ValueGroupEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value present.
        /// </summary>
        internal static string EgsEcfParser_EcfErrors_ValueNull {
            get {
                return ResourceManager.GetString("EgsEcfParser.EcfErrors.ValueNull", resourceCulture);
            }
        }
    }
}
