//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class InternalSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InternalSettings defaultInstance = ((InternalSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InternalSettings())));
        
        public static InternalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EgsEcfFile|*.ecf")]
        public string EgsEcfEditorApp_FileDialogFilter {
            get {
                return ((string)(this["EgsEcfEditorApp_FileDialogFilter"]));
            }
            set {
                this["EgsEcfEditorApp_FileDialogFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ecf")]
        public string EgsEcfEditorApp_FileDialogExtension {
            get {
                return ((string)(this["EgsEcfEditorApp_FileDialogExtension"]));
            }
            set {
                this["EgsEcfEditorApp_FileDialogExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content\\Configuration")]
        public string EgsEcfEditorApp_EgsConfigDirectory {
            get {
                return ((string)(this["EgsEcfEditorApp_EgsConfigDirectory"]));
            }
            set {
                this["EgsEcfEditorApp_EgsConfigDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("383120")]
        public string EgsEcfEditorApp_EgsSteamAppId {
            get {
                return ((string)(this["EgsEcfEditorApp_EgsSteamAppId"]));
            }
            set {
                this["EgsEcfEditorApp_EgsSteamAppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteamApps")]
        public string EgsEcfEditorApp_SteamAppsFolderName {
            get {
                return ((string)(this["EgsEcfEditorApp_SteamAppsFolderName"]));
            }
            set {
                this["EgsEcfEditorApp_SteamAppsFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallPath")]
        public string EgsEcfEditorApp_InstallPathRegistryValue {
            get {
                return ((string)(this["EgsEcfEditorApp_InstallPathRegistryValue"]));
            }
            set {
                this["EgsEcfEditorApp_InstallPathRegistryValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Valve\\Steam")]
        public string EgsEcfEditorApp_SteamRegistryKey32 {
            get {
                return ((string)(this["EgsEcfEditorApp_SteamRegistryKey32"]));
            }
            set {
                this["EgsEcfEditorApp_SteamRegistryKey32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Valve\\Steam")]
        public string EgsEcfEditorApp_SteamRegistryKey64 {
            get {
                return ((string)(this["EgsEcfEditorApp_SteamRegistryKey64"]));
            }
            set {
                this["EgsEcfEditorApp_SteamRegistryKey64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acf")]
        public string EgsEcfEditorApp_SteamAppManifestFileExtension {
            get {
                return ((string)(this["EgsEcfEditorApp_SteamAppManifestFileExtension"]));
            }
            set {
                this["EgsEcfEditorApp_SteamAppManifestFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("libraryfolders.vdf")]
        public string EgsEcfEditorApp_SteamLibraryConfigFileName {
            get {
                return ((string)(this["EgsEcfEditorApp_SteamLibraryConfigFileName"]));
            }
            set {
                this["EgsEcfEditorApp_SteamLibraryConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("path")]
        public string EgsEcfEditorApp_AppRootPathSteamConfigKey {
            get {
                return ((string)(this["EgsEcfEditorApp_AppRootPathSteamConfigKey"]));
            }
            set {
                this["EgsEcfEditorApp_AppRootPathSteamConfigKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("installdir")]
        public string EgsEcfEditorApp_AppPathSteamConfigKey {
            get {
                return ((string)(this["EgsEcfEditorApp_AppPathSteamConfigKey"]));
            }
            set {
                this["EgsEcfEditorApp_AppPathSteamConfigKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("common")]
        public string EgsEcfEditorApp_SteamCommonFolderName {
            get {
                return ((string)(this["EgsEcfEditorApp_SteamCommonFolderName"]));
            }
            set {
                this["EgsEcfEditorApp_SteamCommonFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EcfFileDefinitions")]
        public string EgsEcfEditorApp_DefinitionDefaultBaseFolder {
            get {
                return ((string)(this["EgsEcfEditorApp_DefinitionDefaultBaseFolder"]));
            }
            set {
                this["EgsEcfEditorApp_DefinitionDefaultBaseFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VanillaEcfDefinition_BlocksConfig.xml")]
        public string EgsEcfEditorApp_DefinitionTemplateFileName {
            get {
                return ((string)(this["EgsEcfEditorApp_DefinitionTemplateFileName"]));
            }
            set {
                this["EgsEcfEditorApp_DefinitionTemplateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(", ")]
        public string EgsEcfEditorApp_ValueSeperator {
            get {
                return ((string)(this["EgsEcfEditorApp_ValueSeperator"]));
            }
            set {
                this["EgsEcfEditorApp_ValueSeperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(": ")]
        public string EgsEcfEditorApp_GroupSeperator {
            get {
                return ((string)(this["EgsEcfEditorApp_GroupSeperator"]));
            }
            set {
                this["EgsEcfEditorApp_GroupSeperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string EgsEcfEditorApp_ValuesPendingIndicator {
            get {
                return ((string)(this["EgsEcfEditorApp_ValuesPendingIndicator"]));
            }
            set {
                this["EgsEcfEditorApp_ValuesPendingIndicator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EgsEcfEditorApp_ValueMaxCount {
            get {
                return ((int)(this["EgsEcfEditorApp_ValueMaxCount"]));
            }
            set {
                this["EgsEcfEditorApp_ValueMaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EgsEcfEditorApp_GroupMaxCount {
            get {
                return ((int)(this["EgsEcfEditorApp_GroupMaxCount"]));
            }
            set {
                this["EgsEcfEditorApp_GroupMaxCount"] = value;
            }
        }
    }
}
