//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class InternalSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InternalSettings defaultInstance = ((InternalSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InternalSettings())));
        
        public static InternalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EgsEcfFile|*.ecf")]
        public string EgsEcfEditorApp_FileHandling_FileDialogFilter {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_FileDialogFilter"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_FileDialogFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ecf")]
        public string EgsEcfEditorApp_FileHandling_FileDialogExtension {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_FileDialogExtension"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_FileDialogExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content\\Configuration")]
        public string EgsEcfEditorApp_FileHandling_EGSConfigDirectory {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_EGSConfigDirectory"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_EGSConfigDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("383120")]
        public string EgsEcfEditorApp_EGSSteamAppId {
            get {
                return ((string)(this["EgsEcfEditorApp_EGSSteamAppId"]));
            }
            set {
                this["EgsEcfEditorApp_EGSSteamAppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteamApps")]
        public string EgsEcfEditorApp_FileHandling_SteamAppsFolderName {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_SteamAppsFolderName"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_SteamAppsFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallPath")]
        public string EgsEcfEditorApp_FileHandling_InstallPathRegistryValue {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_InstallPathRegistryValue"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_InstallPathRegistryValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Valve\\Steam")]
        public string EgsEcfEditorApp_FileHandling_SteamRegistryKey32 {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_SteamRegistryKey32"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_SteamRegistryKey32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Valve\\Steam")]
        public string EgsEcfEditorApp_FileHandling_SteamRegistryKey64 {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_SteamRegistryKey64"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_SteamRegistryKey64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acf")]
        public string EgsEcfEditorApp_FileHandling_SteamAppManifestFileExtension {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_SteamAppManifestFileExtension"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_SteamAppManifestFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("libraryfolders.vdf")]
        public string EgsEcfEditorApp_FileHandling_SteamLibraryConfigFileName {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_SteamLibraryConfigFileName"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_SteamLibraryConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("path")]
        public string EgsEcfEditorApp_FileHandling_AppRootPathSteamConfigKey {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_AppRootPathSteamConfigKey"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_AppRootPathSteamConfigKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("installdir")]
        public string EgsEcfEditorApp_FileHandling_AppPathSteamConfigKey {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_AppPathSteamConfigKey"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_AppPathSteamConfigKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("common")]
        public string EgsEcfEditorApp_FileHandling_SteamCommonFolderName {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_SteamCommonFolderName"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_SteamCommonFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EcfFileDefinitions")]
        public string EgsEcfEditorApp_FileHandling_DefinitionDefaultBaseFolder {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_DefinitionDefaultBaseFolder"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_DefinitionDefaultBaseFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VanillaEcfDefinition_BlocksConfig.xml")]
        public string EgsEcfEditorApp_FileHandling_DefinitionTemplateFileName {
            get {
                return ((string)(this["EgsEcfEditorApp_FileHandling_DefinitionTemplateFileName"]));
            }
            set {
                this["EgsEcfEditorApp_FileHandling_DefinitionTemplateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(", ")]
        public string EgsEcfEditorApp_ParameterDisplay_ValueSeperator {
            get {
                return ((string)(this["EgsEcfEditorApp_ParameterDisplay_ValueSeperator"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterDisplay_ValueSeperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(": ")]
        public string EgsEcfEditorApp_ParameterDisplay_GroupSeperator {
            get {
                return ((string)(this["EgsEcfEditorApp_ParameterDisplay_GroupSeperator"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterDisplay_GroupSeperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string EgsEcfEditorApp_ParameterDisplay_ValuesPendingIndicator {
            get {
                return ((string)(this["EgsEcfEditorApp_ParameterDisplay_ValuesPendingIndicator"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterDisplay_ValuesPendingIndicator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EgsEcfEditorApp_ParameterDisplay_ValueMaxCount {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterDisplay_ValueMaxCount"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterDisplay_ValueMaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EgsEcfEditorApp_ParameterDisplay_GroupMaxCount {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterDisplay_GroupMaxCount"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterDisplay_GroupMaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int EgsEcfEditorApp_ParameterDisplay_ValueMaxLenght {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterDisplay_ValueMaxLenght"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterDisplay_ValueMaxLenght"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int EcfFileCAMDialog_PageSize {
            get {
                return ((int)(this["EcfFileCAMDialog_PageSize"]));
            }
            set {
                this["EcfFileCAMDialog_PageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int EgsEcfEditorApp_ParameterHandling_UnlockLevelMaxValue {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterHandling_UnlockLevelMaxValue"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterHandling_UnlockLevelMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EgsEcfEditorApp_ParameterHandling_UnlockLevelMinValue {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterHandling_UnlockLevelMinValue"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterHandling_UnlockLevelMinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int EgsEcfEditorApp_ParameterHandling_UnlockCostMaxValue {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterHandling_UnlockCostMaxValue"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterHandling_UnlockCostMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgsEcfEditorApp_ParameterHandling_UnlockCostMinValue {
            get {
                return ((int)(this["EgsEcfEditorApp_ParameterHandling_UnlockCostMinValue"]));
            }
            set {
                this["EgsEcfEditorApp_ParameterHandling_UnlockCostMinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public char SettingsDialog_MultiValueSeperator {
            get {
                return ((char)(this["SettingsDialog_MultiValueSeperator"]));
            }
            set {
                this["SettingsDialog_MultiValueSeperator"] = value;
            }
        }
    }
}
