//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EgsEcfFile|*.ecf")]
        public string Filter_EgsEcfFile {
            get {
                return ((string)(this["Filter_EgsEcfFile"]));
            }
            set {
                this["Filter_EgsEcfFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ecf")]
        public string Extension_EgsConfigFile {
            get {
                return ((string)(this["Extension_EgsConfigFile"]));
            }
            set {
                this["Extension_EgsConfigFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Directory_FileDialog_Last {
            get {
                return ((string)(this["Directory_FileDialog_Last"]));
            }
            set {
                this["Directory_FileDialog_Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content\\Configuration")]
        public string Directory_EgsConfig {
            get {
                return ((string)(this["Directory_EgsConfig"]));
            }
            set {
                this["Directory_EgsConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("383120")]
        public string SteamAppId_Egs {
            get {
                return ((string)(this["SteamAppId_Egs"]));
            }
            set {
                this["SteamAppId_Egs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteamApps")]
        public string FolderName_SteamApps {
            get {
                return ((string)(this["FolderName_SteamApps"]));
            }
            set {
                this["FolderName_SteamApps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallPath")]
        public string RegistryValue_InstallPath {
            get {
                return ((string)(this["RegistryValue_InstallPath"]));
            }
            set {
                this["RegistryValue_InstallPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Valve\\Steam")]
        public string RegistryKey32_Steam {
            get {
                return ((string)(this["RegistryKey32_Steam"]));
            }
            set {
                this["RegistryKey32_Steam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Valve\\Steam")]
        public string RegistryKey64_Steam {
            get {
                return ((string)(this["RegistryKey64_Steam"]));
            }
            set {
                this["RegistryKey64_Steam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acf")]
        public string Extension_SteamAppManifestFile {
            get {
                return ((string)(this["Extension_SteamAppManifestFile"]));
            }
            set {
                this["Extension_SteamAppManifestFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("libraryfolders.vdf")]
        public string FileName_SteamLibraryConfig {
            get {
                return ((string)(this["FileName_SteamLibraryConfig"]));
            }
            set {
                this["FileName_SteamLibraryConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("path")]
        public string SteamConfigKey_AppRootPath {
            get {
                return ((string)(this["SteamConfigKey_AppRootPath"]));
            }
            set {
                this["SteamConfigKey_AppRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("installdir")]
        public string SteamConfigKey_AppPath {
            get {
                return ((string)(this["SteamConfigKey_AppPath"]));
            }
            set {
                this["SteamConfigKey_AppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("common")]
        public string FolderName_SteamCommon {
            get {
                return ((string)(this["FolderName_SteamCommon"]));
            }
            set {
                this["FolderName_SteamCommon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Size_View_Tree_Width {
            get {
                return ((int)(this["Size_View_Tree_Width"]));
            }
            set {
                this["Size_View_Tree_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Size_View_Info_Width {
            get {
                return ((int)(this["Size_View_Info_Width"]));
            }
            set {
                this["Size_View_Info_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int Size_View_Error_Height {
            get {
                return ((int)(this["Size_View_Error_Height"]));
            }
            set {
                this["Size_View_Error_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int Size_App_Width {
            get {
                return ((int)(this["Size_App_Width"]));
            }
            set {
                this["Size_App_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int Size_App_Height {
            get {
                return ((int)(this["Size_App_Height"]));
            }
            set {
                this["Size_App_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Location_App_X {
            get {
                return ((int)(this["Location_App_X"]));
            }
            set {
                this["Location_App_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Location_App_Y {
            get {
                return ((int)(this["Location_App_Y"]));
            }
            set {
                this["Location_App_Y"] = value;
            }
        }
    }
}
