//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextRecources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextRecources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgsEcfEditorApp.Properties.TextRecources", typeof(TextRecources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deprecated items found.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_EmptyDataText {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of errors shown at once.
        /// </summary>
        internal static string EcfErrorView_ToolTip_ErrorCountSelector {
            get {
                return ResourceManager.GetString("EcfErrorView_ToolTip_ErrorCountSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of errors shown.
        /// </summary>
        internal static string EcfErrorView_ToolTip_ErrorGroupSelector {
            get {
                return ResourceManager.GetString("EcfErrorView_ToolTip_ErrorGroupSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets alphabetical sorting order.
        /// </summary>
        internal static string EcfErrorView_ToolTip_ErrorSorterAlphabeticOrder {
            get {
                return ResourceManager.GetString("EcfErrorView_ToolTip_ErrorSorterAlphabeticOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the sorting direction.
        /// </summary>
        internal static string EcfErrorView_ToolTip_ErrorSorterDirection {
            get {
                return ResourceManager.GetString("EcfErrorView_ToolTip_ErrorSorterDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets order of occurance.
        /// </summary>
        internal static string EcfErrorView_ToolTip_ErrorSorterOriginOrder {
            get {
                return ResourceManager.GetString("EcfErrorView_ToolTip_ErrorSorterOriginOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to differing root elements overall.
        /// </summary>
        internal static string EcfFileCAMDialog_RootElementsOverall {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_RootElementsOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates / deactivates all elements which would be added.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_ChangeAllAddItems {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_ChangeAllAddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates / deactivates all elements which would be removed.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_ChangeAllRemoveItems {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_ChangeAllRemoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates / deactivates all elements which would be updated.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_ChangeAllUnequalItems {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_ChangeAllUnequalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrates the selected changes from the right into the left file.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_DoMergeLeft {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_DoMergeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrates the selected changes from the left into the right file.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_DoMergeRight {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_DoMergeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select next page.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_PageDown {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previous page.
        /// </summary>
        internal static string EcfFileCAMDialog_ToolTip_PageUp {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_ToolTip_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare running.
        /// </summary>
        internal static string EcfFileCamWorkerDialog_Comparing {
            get {
                return ResourceManager.GetString("EcfFileCamWorkerDialog_Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge running.
        /// </summary>
        internal static string EcfFileCamWorkerDialog_Merging {
            get {
                return ResourceManager.GetString("EcfFileCamWorkerDialog_Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a new file the encoding has to be selected. The already selected default encoding should be suitable in most cases..
        /// </summary>
        internal static string EcfFileOpenDialog_ToolTip_Encoding {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_ToolTip_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the file name the format is guessed. When guessing fails or is not correct, select the desired format definition manually..
        /// </summary>
        internal static string EcfFileOpenDialog_ToolTip_FormatDefinition {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_ToolTip_FormatDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a new file the new line symbol has to be selected. The already selected default symbol should be suitable in most cases..
        /// </summary>
        internal static string EcfFileOpenDialog_ToolTip_NewLineSymbol {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_ToolTip_NewLineSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one property is not selected properly. Please check the inputs!.
        /// </summary>
        internal static string EcfFilePropertiesDialog_PropertiesIncomplete {
            get {
                return ResourceManager.GetString("EcfFilePropertiesDialog_PropertiesIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition found.
        /// </summary>
        internal static string EcfInfoView_NoDefinition {
            get {
                return ResourceManager.GetString("EcfInfoView_NoDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one comment line is empty.
        /// </summary>
        internal static string EcfItemEditingDialog_AnyCommentLineEmpty {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_AnyCommentLineEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block editing aborted.
        /// </summary>
        internal static string EcfItemEditingDialog_BlockEditingAborted {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_BlockEditingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not be found in the item list.
        /// </summary>
        internal static string EcfItemEditingDialog_CouldNotBeFoundInTheItemList {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_CouldNotBeFoundInTheItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has no unique identifier.
        /// </summary>
        internal static string EcfItemEditingDialog_HasNoUniqueIdentifier {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_HasNoUniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already used by.
        /// </summary>
        internal static string EcfItemEditingDialog_IsAlreadyUsedBy {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_IsAlreadyUsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is still referenced by.
        /// </summary>
        internal static string EcfItemEditingDialog_IsStillReferencedBy {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_IsStillReferencedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addable Parameter available.
        /// </summary>
        internal static string EcfItemEditingDialog_NoAddableParameterAvailable {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoAddableParameterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item adding not possible without ecf file reference.
        /// </summary>
        internal static string EcfItemEditingDialog_NoAddingWithoutFile {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoAddingWithoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block adding not allowed without PostMark definition.
        /// </summary>
        internal static string EcfItemEditingDialog_NoBlockAddingWithoutPostMarkDefinition {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoBlockAddingWithoutPostMarkDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Block adding not allowed without a type definition.
        /// </summary>
        internal static string EcfItemEditingDialog_NoChildBlockAddingWithoutTypeDefinition {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoChildBlockAddingWithoutTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition available for.
        /// </summary>
        internal static string EcfItemEditingDialog_NoDefinitionAvailableFor {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoDefinitionAvailableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition could be found for parameter.
        /// </summary>
        internal static string EcfItemEditingDialog_NoDefinitionFoundForParameter {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoDefinitionFoundForParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editable item reference provided.
        /// </summary>
        internal static string EcfItemEditingDialog_NoEditableItemProvided {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoEditableItemProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item editing not possible without ecf file reference.
        /// </summary>
        internal static string EcfItemEditingDialog_NoEditingWithoutFile {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoEditingWithoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter adding not allowed without definitions.
        /// </summary>
        internal static string EcfItemEditingDialog_NoParameterAddingWithoutDefinitions {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoParameterAddingWithoutDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter adding not allowed without parent element.
        /// </summary>
        internal static string EcfItemEditingDialog_NoParameterAddingWithoutParent {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoParameterAddingWithoutParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter editing not allowed without definitions.
        /// </summary>
        internal static string EcfItemEditingDialog_NoParameterEditingWithoutDefinitions {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoParameterEditingWithoutDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter editing not allowed without parent element.
        /// </summary>
        internal static string EcfItemEditingDialog_NoParameterEditingWithoutParent {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoParameterEditingWithoutParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Block adding not allowed without a type definition.
        /// </summary>
        internal static string EcfItemEditingDialog_NoRootBlockAddingWithoutTypeDefinition {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoRootBlockAddingWithoutTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selectable Parameter available.
        /// </summary>
        internal static string EcfItemEditingDialog_NoSelectableParameterAvailable {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NoSelectableParameterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selected.
        /// </summary>
        internal static string EcfItemEditingDialog_NotSelected {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation mode not suitable for adding operation.
        /// </summary>
        internal static string EcfItemEditingDialog_OperationModeNotSuitableForAdding {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_OperationModeNotSuitableForAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter editing aborted.
        /// </summary>
        internal static string EcfItemEditingDialog_ParameterEditingAborted {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ParameterEditingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter matrix editing feature not allow unknown parameters.
        /// </summary>
        internal static string EcfItemEditingDialog_ParameterMatrixForUnknownParametersNotAllowed {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ParameterMatrixForUnknownParametersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter matrix editing feature not allow parameters without values.
        /// </summary>
        internal static string EcfItemEditingDialog_ParameterMatrixForValuelessParametersNotAllowed {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ParameterMatrixForValuelessParametersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute id value.
        /// </summary>
        internal static string EcfItemEditingDialog_TheIdAttributeValue {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_TheIdAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute name value.
        /// </summary>
        internal static string EcfItemEditingDialog_TheNameAttributeValue {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_TheNameAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old attribute name value.
        /// </summary>
        internal static string EcfItemEditingDialog_TheOldNameAttributeValue {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_TheOldNameAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced item.
        /// </summary>
        internal static string EcfItemEditingDialog_TheReferencedItem {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_TheReferencedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a value cell after the selected cell.
        /// </summary>
        internal static string EcfItemEditingDialog_ToolTip_AddValue {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ToolTip_AddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a value group row after the selected cell.
        /// </summary>
        internal static string EcfItemEditingDialog_ToolTip_AddValueGroup {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ToolTip_AddValueGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected value slot.
        /// </summary>
        internal static string EcfItemEditingDialog_ToolTip_RemoveValue {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ToolTip_RemoveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected value group row.
        /// </summary>
        internal static string EcfItemEditingDialog_ToolTip_RemoveValueGroup {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ToolTip_RemoveValueGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add template failed.
        /// </summary>
        internal static string EcfItemHandlingSupport_AddTemplateFailed {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_AddTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Template Definition failed.
        /// </summary>
        internal static string EcfItemHandlingSupport_AddToTemplateDefinitionFailed {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_AddToTemplateDefinitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement of Definition failed.
        /// </summary>
        internal static string EcfItemHandlingSupport_DefinitionReplacementFailed {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_DefinitionReplacementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has already a template attached.
        /// </summary>
        internal static string EcfItemHandlingSupport_ElementHasAlreadyTemplate {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_ElementHasAlreadyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template file is opened.
        /// </summary>
        internal static string EcfItemHandlingSupport_NoTemplateFileOpened {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_NoTemplateFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No templates for item.
        /// </summary>
        internal static string EcfItemHandlingSupport_NoTemplatesForItem {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_NoTemplatesForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only remove Template (Yes) or delete completely (No)?.
        /// </summary>
        internal static string EcfItemHandlingSupport_OnlyRemoveOrDeleteTemplateQuestion {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_OnlyRemoveOrDeleteTemplateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove template failed.
        /// </summary>
        internal static string EcfItemHandlingSupport_RemoveTemplateFailed {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_RemoveTemplateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file before the Definition is replaced and the file is reloaded?.
        /// </summary>
        internal static string EcfItemHandlingSupport_SaveFileBeforeDefinitionReloadQuestion {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_SaveFileBeforeDefinitionReloadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not opened!.
        /// </summary>
        internal static string EcfItemHandlingSupport_SelectedFileNotOpened {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_SelectedFileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to still used with.
        /// </summary>
        internal static string EcfItemHandlingSupport_StillUsedWith {
            get {
                return ResourceManager.GetString("EcfItemHandlingSupport_StillUsedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items with template.
        /// </summary>
        internal static string EcfItemListingView_AllElementsWithTemplate {
            get {
                return ResourceManager.GetString("EcfItemListingView_AllElementsWithTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items with parameter.
        /// </summary>
        internal static string EcfItemListingView_AllItemsWithParameter {
            get {
                return ResourceManager.GetString("EcfItemListingView_AllItemsWithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Parameters with value.
        /// </summary>
        internal static string EcfItemListingView_AllParametersWithValue {
            get {
                return ResourceManager.GetString("EcfItemListingView_AllParametersWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All templates for item.
        /// </summary>
        internal static string EcfItemListingView_AllTemplatesForItem {
            get {
                return ResourceManager.GetString("EcfItemListingView_AllTemplatesForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All templates with item.
        /// </summary>
        internal static string EcfItemListingView_AllTemplatesWithItem {
            get {
                return ResourceManager.GetString("EcfItemListingView_AllTemplatesWithItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Parameters are inherited to the selected tree element.
        /// </summary>
        internal static string EcfParameterView_ToolTip_InheritedColumn {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_InheritedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Parameters overwriting an inherited parameter.
        /// </summary>
        internal static string EcfParameterView_ToolTip_OverwritingColumn {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_OverwritingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of parameters shown at once.
        /// </summary>
        internal static string EcfParameterView_ToolTip_ParameterCountSelector {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_ParameterCountSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of parameters shown.
        /// </summary>
        internal static string EcfParameterView_ToolTip_ParameterGroupSelector {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_ParameterGroupSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets alphabetical sorting order for parameter names.
        /// </summary>
        internal static string EcfParameterView_ToolTip_ParameterSorterAlphabeticOrder {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_ParameterSorterAlphabeticOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the sorting direction.
        /// </summary>
        internal static string EcfParameterView_ToolTip_ParameterSorterDirection {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_ParameterSorterDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets hierarchical sorting order.
        /// </summary>
        internal static string EcfParameterView_ToolTip_ParameterSorterOriginOrder {
            get {
                return ResourceManager.GetString("EcfParameterView_ToolTip_ParameterSorterOriginOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really reset all settings to default?.
        /// </summary>
        internal static string EcfSettingsDialog_ReallyResetAllQuestion {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ReallyResetAllQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, a item will try to use the original parsed data if the data from the editor are invalid.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_AllowFallbackToParsedData {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_AllowFallbackToParsedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value if an element has no unlock cost value specified.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_DefaultValueUnlockCost {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_DefaultValueUnlockCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value if an element has no unlock level value specified.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_DefaultValueUnlockLevel {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_DefaultValueUnlockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the initial value for the visible item count setting of the error view.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_ErrorViewSorterInitCount {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_ErrorViewSorterInitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the game version which definitions will be used.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_GameVersionFolder {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_GameVersionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, items with at least one invalid sub item will not be saved.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_InvalidateParentsOnError {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_InvalidateParentsOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the parameter key which contains the names of the trees the element belongs to.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_ParameterKeyTechTreeNames {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_ParameterKeyTechTreeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the parameter key which contains the tech tree parent element name.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_ParameterKeyTechTreeParentName {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_ParameterKeyTechTreeParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the parameter key which contains the unlock cost value.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_ParameterKeyUnlockCost {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_ParameterKeyUnlockCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the parameter key which contains the unlock level value.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_ParameterKeyUnlockLevel {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_ParameterKeyUnlockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the initial value for the visible item count setting of the parameter view.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_ParameterViewSorterInitCount {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_ParameterViewSorterInitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, the initial state of the filter setting for comments will be set to visible.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_TreeViewFilterCommentsInitActive {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_TreeViewFilterCommentsInitActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, the initial state of the filter setting for data blocks will be set to visible.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_TreeViewFilterDataBlocksInitActive {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_TreeViewFilterDataBlocksInitActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, the initial state of the filter setting for parameters will be set to visible.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_TreeViewFilterParametersInitActive {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_TreeViewFilterParametersInitActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the initial value for the visible item count setting of the tree view.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_TreeViewSorterInitCount {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_TreeViewSorterInitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If activated, at saving the file only valid items will be written.
        /// </summary>
        internal static string EcfSettingsDialog_ToolTip_WriteOnlyValidItems {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_ToolTip_WriteOnlyValidItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved setting changes. Really close and discards changes?.
        /// </summary>
        internal static string EcfSettingsDialog_UnsavedReallyCloseQuestion {
            get {
                return ResourceManager.GetString("EcfSettingsDialog_UnsavedReallyCloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an element of the selected type.
        /// </summary>
        internal static string EcfTabPage_ToolTip_Add {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of several elements and values at once.
        /// </summary>
        internal static string EcfTabPage_ToolTip_ChangeComplex {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_ChangeComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change single or few values of selected elements.
        /// </summary>
        internal static string EcfTabPage_ToolTip_ChangeSimple {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_ChangeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the selected elements to the clipboard.
        /// </summary>
        internal static string EcfTabPage_ToolTip_CopyElements {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_CopyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies the filter to views.
        /// </summary>
        internal static string EcfTabPage_ToolTip_FilterApplyButton {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_FilterApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the filter and refreshes the views.
        /// </summary>
        internal static string EcfTabPage_ToolTip_FilterClearButton {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_FilterClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected elements downwards.
        /// </summary>
        internal static string EcfTabPage_ToolTip_MoveDown {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected elements upwards.
        /// </summary>
        internal static string EcfTabPage_ToolTip_MoveUp {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textual parameter search filter on parameter values (Case sensitive Like).
        /// </summary>
        internal static string EcfTabPage_ToolTip_ParameterLikeInput {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_ParameterLikeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the visible parameter items.
        /// </summary>
        internal static string EcfTabPage_ToolTip_ParameterSelector {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_ParameterSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastes the copied elements from the clipboard to the selected file and location.
        /// </summary>
        internal static string EcfTabPage_ToolTip_PasteElements {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_PasteElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last undo.
        /// </summary>
        internal static string EcfTabPage_ToolTip_Redo {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected elements.
        /// </summary>
        internal static string EcfTabPage_ToolTip_Remove {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles between &quot;Show all&quot;, &quot;Show faulty only&quot; and &quot;Show non faulty only&quot;.
        /// </summary>
        internal static string EcfTabPage_ToolTip_TreeErrorDisplayModeSelector {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_TreeErrorDisplayModeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the visible tree item types.
        /// </summary>
        internal static string EcfTabPage_ToolTip_TreeItemTypeSelector {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_TreeItemTypeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textual tree item search filter on display node name (Case sensitive Like).
        /// </summary>
        internal static string EcfTabPage_ToolTip_TreeLikeInput {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_TreeLikeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last change.
        /// </summary>
        internal static string EcfTabPage_ToolTip_Undo {
            get {
                return ResourceManager.GetString("EcfTabPage_ToolTip_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of the element settings failed.
        /// </summary>
        internal static string EcfTechTreeDialog_ElementSettingsUpdateError {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ElementSettingsUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New TechTree.
        /// </summary>
        internal static string EcfTechTreeDialog_NewTreeName {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_NewTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really remove complete TechTree?.
        /// </summary>
        internal static string EcfTechTreeDialog_ReallyRemoveTechTreeQuestion {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ReallyRemoveTechTreeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file for the type.
        /// </summary>
        internal static string EcfTechTreeDialog_SelectFileForType {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_SelectFileForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TechTree name is already used by another TechTree!.
        /// </summary>
        internal static string EcfTechTreeDialog_TechTreeNameAlreadyUsed {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_TechTreeNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new empty tech tree.
        /// </summary>
        internal static string EcfTechTreeDialog_ToolTip_AddTree {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ToolTip_AddTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the selected tech tree to clipboard.
        /// </summary>
        internal static string EcfTechTreeDialog_ToolTip_CopyTree {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ToolTip_CopyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new tech tree from the clipboard.
        /// </summary>
        internal static string EcfTechTreeDialog_ToolTip_PasteTree {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ToolTip_PasteTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected tech tree.
        /// </summary>
        internal static string EcfTechTreeDialog_ToolTip_RemoveTree {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ToolTip_RemoveTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renames the selected tech tree.
        /// </summary>
        internal static string EcfTechTreeDialog_ToolTip_RenameTree {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_ToolTip_RenameTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable element selected.
        /// </summary>
        internal static string EcfTechTreeItemEditorDialog_NoElementSelected {
            get {
                return ResourceManager.GetString("EcfTechTreeItemEditorDialog_NoElementSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of tree items shown at once.
        /// </summary>
        internal static string EcfTreeView_ToolTip_TreeItemCountSelector {
            get {
                return ResourceManager.GetString("EcfTreeView_ToolTip_TreeItemCountSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of tree items shown.
        /// </summary>
        internal static string EcfTreeView_ToolTip_TreeItemGroupSelector {
            get {
                return ResourceManager.GetString("EcfTreeView_ToolTip_TreeItemGroupSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets alphabetical sorting order for element names.
        /// </summary>
        internal static string EcfTreeView_ToolTip_TreeSorterAlphabeticOrder {
            get {
                return ResourceManager.GetString("EcfTreeView_ToolTip_TreeSorterAlphabeticOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the sorting direction.
        /// </summary>
        internal static string EcfTreeView_ToolTip_TreeSorterDirection {
            get {
                return ResourceManager.GetString("EcfTreeView_ToolTip_TreeSorterDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets original sorting order (from File).
        /// </summary>
        internal static string EcfTreeView_ToolTip_TreeSorterOriginOrder {
            get {
                return ResourceManager.GetString("EcfTreeView_ToolTip_TreeSorterOriginOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in at least one tab. Really close all tabs?.
        /// </summary>
        internal static string EgsEcfEditorApp_CloseAllTabsWithUnsaved {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_CloseAllTabsWithUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in at least one tab. Really close the app?.
        /// </summary>
        internal static string EgsEcfEditorApp_CloseAppWithUnsaved {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_CloseAppWithUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in the selected tab. Really close this tab?.
        /// </summary>
        internal static string EgsEcfEditorApp_CloseTabWithUnsaved {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_CloseTabWithUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be created!.
        /// </summary>
        internal static string EgsEcfEditorApp_CreateEcfFileFailed {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_CreateEcfFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesser then two files opened!.
        /// </summary>
        internal static string EgsEcfEditorApp_LesserThenTwoFilesOpened {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_LesserThenTwoFilesOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid file tab selected!.
        /// </summary>
        internal static string EgsEcfEditorApp_NoTabSelected {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_NoTabSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be opened!.
        /// </summary>
        internal static string EgsEcfEditorApp_OpenEcfFileFailed {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_OpenEcfFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in the selected tab. Really reload this tab?.
        /// </summary>
        internal static string EgsEcfEditorApp_OverrideTabWithUnsaved {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_OverrideTabWithUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content could not be reloaded!.
        /// </summary>
        internal static string EgsEcfEditorApp_ReloadEcfFileFailed {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ReloadEcfFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition reloading failed!.
        /// </summary>
        internal static string EgsEcfEditorApp_ReloadFileDefinitionsFailed {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ReloadFileDefinitionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions reloaded successfully!.
        /// </summary>
        internal static string EgsEcfEditorApp_ReloadFileDefinitionsSuccess {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ReloadFileDefinitionsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be saved!.
        /// </summary>
        internal static string EgsEcfEditorApp_SaveEcfFileFailed {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_SaveEcfFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks the format definition of the selected file on deprecated specifications.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_CheckDefinition {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_CheckDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the selected file.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_Close {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all files.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_CloseAll {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compares two files, lists the differences and offers merge options.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_CompareAndMerge {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_CompareAndMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new file.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_New {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens an existing file.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_Open {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the settings dialog.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_OpenSettingsDialog {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_OpenSettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the content from the file.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_Reload {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the format definition data from the XML files.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_ReloadDefinitions {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_ReloadDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces the Definition of the selected file with the latest loaded Definition and reread the content of the file with this Definition  .
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_ReplaceDefinition {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_ReplaceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the selected file.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_Save {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all files.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_SaveAll {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the selected file with new name.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_SaveAs {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a preview for the TechTree based on the open files and provides altering options.
        /// </summary>
        internal static string EgsEcfEditorApp_ToolTip_TechTreeEditor {
            get {
                return ResourceManager.GetString("EgsEcfEditorApp_ToolTip_TechTreeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added to.
        /// </summary>
        internal static string Generic_AddedTo {
            get {
                return ResourceManager.GetString("Generic_AddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change all.
        /// </summary>
        internal static string Generic_ChangeAll {
            get {
                return ResourceManager.GetString("Generic_ChangeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing is not possible due to errors.
        /// </summary>
        internal static string Generic_ContinueImpossibleWithErrors {
            get {
                return ResourceManager.GetString("Generic_ContinueImpossibleWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing the current operation will result in errors. Still continue?.
        /// </summary>
        internal static string Generic_ContinueOperationWithErrorsQuestion {
            get {
                return ResourceManager.GetString("Generic_ContinueOperationWithErrorsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be opened.
        /// </summary>
        internal static string Generic_FileCouldNotBeOpened {
            get {
                return ResourceManager.GetString("Generic_FileCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has error.
        /// </summary>
        internal static string Generic_HasError {
            get {
                return ResourceManager.GetString("Generic_HasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has no value.
        /// </summary>
        internal static string Generic_HasNoValue {
            get {
                return ResourceManager.GetString("Generic_HasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not optional.
        /// </summary>
        internal static string Generic_IsNotOptional {
            get {
                return ResourceManager.GetString("Generic_IsNotOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is referenced by.
        /// </summary>
        internal static string Generic_IsReferencedBy {
            get {
                return ResourceManager.GetString("Generic_IsReferencedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable item selected.
        /// </summary>
        internal static string Generic_NoSuitableSelection {
            get {
                return ResourceManager.GetString("Generic_NoSuitableSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet! :).
        /// </summary>
        internal static string Generic_NotImplementedYet {
            get {
                return ResourceManager.GetString("Generic_NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Generic_Of {
            get {
                return ResourceManager.GetString("Generic_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Generic_Page {
            get {
                return ResourceManager.GetString("Generic_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed from.
        /// </summary>
        internal static string Generic_RemovedFrom {
            get {
                return ResourceManager.GetString("Generic_RemovedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like wise search to reduce the dropdown list.
        /// </summary>
        internal static string ItemSelectorDialog_ToolTip_SearchInfo {
            get {
                return ResourceManager.GetString("ItemSelectorDialog_ToolTip_SearchInfo", resourceCulture);
            }
        }
    }
}
