//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TitleRecources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleRecources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgsEcfEditorApp.Properties.TitleRecources", typeof(TitleRecources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow blank.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_ColumnHeaderAllowBlank {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_ColumnHeaderAllowBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has value.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_ColumnHeaderHasValue {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_ColumnHeaderHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is force escaped.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_ColumnHeaderIsForceEscaped {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_ColumnHeaderIsForceEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare file.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_CompareFile {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_CompareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition file.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_DefinitionFile {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_DefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecated definitions.
        /// </summary>
        internal static string DeprecatedDefinitionsDialog_Header {
            get {
                return ResourceManager.GetString("DeprecatedDefinitionsDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation errors.
        /// </summary>
        internal static string EcfErrorView_CreationErrors {
            get {
                return ResourceManager.GetString("EcfErrorView_CreationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing errors.
        /// </summary>
        internal static string EcfErrorView_EditingErrors {
            get {
                return ResourceManager.GetString("EcfErrorView_EditingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error group.
        /// </summary>
        internal static string EcfErrorView_ErrorGroupColumn {
            get {
                return ResourceManager.GetString("EcfErrorView_ErrorGroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string EcfErrorView_ErrorNumberColumn {
            get {
                return ResourceManager.GetString("EcfErrorView_ErrorNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content error overview.
        /// </summary>
        internal static string EcfErrorView_Header {
            get {
                return ResourceManager.GetString("EcfErrorView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation errors.
        /// </summary>
        internal static string EcfErrorView_InterpretationErrors {
            get {
                return ResourceManager.GetString("EcfErrorView_InterpretationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in editor.
        /// </summary>
        internal static string EcfErrorView_ShowInEditor {
            get {
                return ResourceManager.GetString("EcfErrorView_ShowInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in file.
        /// </summary>
        internal static string EcfErrorView_ShowInFile {
            get {
                return ResourceManager.GetString("EcfErrorView_ShowInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural errors.
        /// </summary>
        internal static string EcfErrorView_StructuralErrors {
            get {
                return ResourceManager.GetString("EcfErrorView_StructuralErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare and Merge.
        /// </summary>
        internal static string EcfFileCAMDialog_Header {
            get {
                return ResourceManager.GetString("EcfFileCAMDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        internal static string EcfFileDialog_CreateFileDialog {
            get {
                return ResourceManager.GetString("EcfFileDialog_CreateFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFile.
        /// </summary>
        internal static string EcfFileDialog_CreateFileName {
            get {
                return ResourceManager.GetString("EcfFileDialog_CreateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string EcfFileLoadingDialog_BarText {
            get {
                return ResourceManager.GetString("EcfFileLoadingDialog_BarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file content.
        /// </summary>
        internal static string EcfFileLoadingDialog_Header {
            get {
                return ResourceManager.GetString("EcfFileLoadingDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File encoding.
        /// </summary>
        internal static string EcfFileOpenDialog_EncodingBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_EncodingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path and name.
        /// </summary>
        internal static string EcfFileOpenDialog_FilePathAndNameBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_FilePathAndNameBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find file.
        /// </summary>
        internal static string EcfFileOpenDialog_FindFileDialog {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_FindFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format definition.
        /// </summary>
        internal static string EcfFileOpenDialog_FormatDefinitionBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_FormatDefinitionBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define new file.
        /// </summary>
        internal static string EcfFileOpenDialog_NewFileDialog {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_NewFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line symbol.
        /// </summary>
        internal static string EcfFileOpenDialog_NewLineSymbolBox {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_NewLineSymbolBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing file.
        /// </summary>
        internal static string EcfFileOpenDialog_OpenFileDialog {
            get {
                return ResourceManager.GetString("EcfFileOpenDialog_OpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element data.
        /// </summary>
        internal static string EcfInfoView_ElementData {
            get {
                return ResourceManager.GetString("EcfInfoView_ElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        internal static string EcfInfoView_Header {
            get {
                return ResourceManager.GetString("EcfInfoView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter data.
        /// </summary>
        internal static string EcfInfoView_ParameterData {
            get {
                return ResourceManager.GetString("EcfInfoView_ParameterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddChildBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddChildBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddComment {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddParameter {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add root block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_AddRootBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_AddRootBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit child block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditChildBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditChildBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditComment {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameter item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditParameter {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Matrix editing.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditParameterMatrix {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditParameterMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit root block item.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_EditRootBlock {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_EditRootBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select element type.
        /// </summary>
        internal static string EcfItemEditingDialog_Header_ElementSelector {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_Header_ElementSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values / Groups.
        /// </summary>
        internal static string EcfItemEditingDialog_ParameterItem_ValuesLabel {
            get {
                return ResourceManager.GetString("EcfItemEditingDialog_ParameterItem_ValuesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item listing.
        /// </summary>
        internal static string EcfItemListingView_Header {
            get {
                return ResourceManager.GetString("EcfItemListingView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter view.
        /// </summary>
        internal static string EcfParameterView_Header {
            get {
                return ResourceManager.GetString("EcfParameterView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inherited.
        /// </summary>
        internal static string EcfParameterView_Header_InheritedParameters {
            get {
                return ResourceManager.GetString("EcfParameterView_Header_InheritedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwriting.
        /// </summary>
        internal static string EcfParameterView_Header_OverwritingParameters {
            get {
                return ResourceManager.GetString("EcfParameterView_Header_OverwritingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string EcfParameterView_ParameterNameColumn {
            get {
                return ResourceManager.GetString("EcfParameterView_ParameterNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string EcfParameterView_ParameterNumberColumn {
            get {
                return ResourceManager.GetString("EcfParameterView_ParameterNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over..
        /// </summary>
        internal static string EcfParameterView_ParameterOverwritingColumn {
            get {
                return ResourceManager.GetString("EcfParameterView_ParameterOverwritingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree element.
        /// </summary>
        internal static string EcfParameterView_ParameterParentColumn {
            get {
                return ResourceManager.GetString("EcfParameterView_ParameterParentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        internal static string EcfParameterView_UnnamedParent {
            get {
                return ResourceManager.GetString("EcfParameterView_UnnamedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechTree preview and edit.
        /// </summary>
        internal static string EcfTechTreeDialog_Header {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from all TechTrees.
        /// </summary>
        internal static string EcfTechTreeDialog_RemoveFromAllMenuItem {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_RemoveFromAllMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from this TechTree.
        /// </summary>
        internal static string EcfTechTreeDialog_RemoveFromThisMenuItem {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_RemoveFromThisMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechTree name input.
        /// </summary>
        internal static string EcfTechTreeDialog_TreeNameInputHeader {
            get {
                return ResourceManager.GetString("EcfTechTreeDialog_TreeNameInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element name.
        /// </summary>
        internal static string EcfTechTreeItemEditorDialog_ElementNameSetting {
            get {
                return ResourceManager.GetString("EcfTechTreeItemEditorDialog_ElementNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Element.
        /// </summary>
        internal static string EcfTechTreeItemEditorDialog_ElementPickerHeader {
            get {
                return ResourceManager.GetString("EcfTechTreeItemEditorDialog_ElementPickerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit element.
        /// </summary>
        internal static string EcfTechTreeItemEditorDialog_Header {
            get {
                return ResourceManager.GetString("EcfTechTreeItemEditorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock cost.
        /// </summary>
        internal static string EcfTechTreeItemEditorDialog_UnlockCostSetting {
            get {
                return ResourceManager.GetString("EcfTechTreeItemEditorDialog_UnlockCostSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock level.
        /// </summary>
        internal static string EcfTechTreeItemEditorDialog_UnlockLevelSetting {
            get {
                return ResourceManager.GetString("EcfTechTreeItemEditorDialog_UnlockLevelSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree items.
        /// </summary>
        internal static string EcfTreeView_FilterSelector_Elements {
            get {
                return ResourceManager.GetString("EcfTreeView_FilterSelector_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view.
        /// </summary>
        internal static string EcfTreeView_Header {
            get {
                return ResourceManager.GetString("EcfTreeView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Generic_Abort {
            get {
                return ResourceManager.GetString("Generic_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Generic_Active {
            get {
                return ResourceManager.GetString("Generic_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Generic_Add {
            get {
                return ResourceManager.GetString("Generic_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add after.
        /// </summary>
        internal static string Generic_AddAfter {
            get {
                return ResourceManager.GetString("Generic_AddAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to.
        /// </summary>
        internal static string Generic_AddTo {
            get {
                return ResourceManager.GetString("Generic_AddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Generic_Attention {
            get {
                return ResourceManager.GetString("Generic_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Generic_Attribute {
            get {
                return ResourceManager.GetString("Generic_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Generic_Attributes {
            get {
                return ResourceManager.GetString("Generic_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Generic_Author {
            get {
                return ResourceManager.GetString("Generic_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Generic_BackButton {
            get {
                return ResourceManager.GetString("Generic_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Generic_Change {
            get {
                return ResourceManager.GetString("Generic_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child item.
        /// </summary>
        internal static string Generic_ChildElement {
            get {
                return ResourceManager.GetString("Generic_ChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child items.
        /// </summary>
        internal static string Generic_ChildElements {
            get {
                return ResourceManager.GetString("Generic_ChildElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Generic_Comment {
            get {
                return ResourceManager.GetString("Generic_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Generic_Comments {
            get {
                return ResourceManager.GetString("Generic_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Generic_Copy {
            get {
                return ResourceManager.GetString("Generic_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Generic_Copying {
            get {
                return ResourceManager.GetString("Generic_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Generic_Cost {
            get {
                return ResourceManager.GetString("Generic_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item.
        /// </summary>
        internal static string Generic_DataElement {
            get {
                return ResourceManager.GetString("Generic_DataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data items.
        /// </summary>
        internal static string Generic_DataElements {
            get {
                return ResourceManager.GetString("Generic_DataElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type.
        /// </summary>
        internal static string Generic_DataType {
            get {
                return ResourceManager.GetString("Generic_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string Generic_Definitions {
            get {
                return ResourceManager.GetString("Generic_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Generic_Element {
            get {
                return ResourceManager.GetString("Generic_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Generic_Elements {
            get {
                return ResourceManager.GetString("Generic_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Generic_Errors {
            get {
                return ResourceManager.GetString("Generic_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Generic_File {
            get {
                return ResourceManager.GetString("Generic_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Generic_Group {
            get {
                return ResourceManager.GetString("Generic_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Generic_Info {
            get {
                return ResourceManager.GetString("Generic_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        internal static string Generic_Inherited {
            get {
                return ResourceManager.GetString("Generic_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is optional.
        /// </summary>
        internal static string Generic_IsOptional {
            get {
                return ResourceManager.GetString("Generic_IsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Generic_Item {
            get {
                return ResourceManager.GetString("Generic_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Generic_Level {
            get {
                return ResourceManager.GetString("Generic_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string Generic_License {
            get {
                return ResourceManager.GetString("Generic_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string Generic_LineNumber {
            get {
                return ResourceManager.GetString("Generic_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Generic_Manual {
            get {
                return ResourceManager.GetString("Generic_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Generic_Name {
            get {
                return ResourceManager.GetString("Generic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string Generic_Names {
            get {
                return ResourceManager.GetString("Generic_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string Generic_Number_Short {
            get {
                return ResourceManager.GetString("Generic_Number_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Generic_Parameter {
            get {
                return ResourceManager.GetString("Generic_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Generic_Parameters {
            get {
                return ResourceManager.GetString("Generic_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent element.
        /// </summary>
        internal static string Generic_ParentElement {
            get {
                return ResourceManager.GetString("Generic_ParentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Generic_Paste {
            get {
                return ResourceManager.GetString("Generic_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste after.
        /// </summary>
        internal static string Generic_PasteAfter {
            get {
                return ResourceManager.GetString("Generic_PasteAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste to.
        /// </summary>
        internal static string Generic_PasteTo {
            get {
                return ResourceManager.GetString("Generic_PasteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick item.
        /// </summary>
        internal static string Generic_PickItem {
            get {
                return ResourceManager.GetString("Generic_PickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post mark.
        /// </summary>
        internal static string Generic_PostMark {
            get {
                return ResourceManager.GetString("Generic_PostMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre mark.
        /// </summary>
        internal static string Generic_PreMark {
            get {
                return ResourceManager.GetString("Generic_PreMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Generic_Properties {
            get {
                return ResourceManager.GetString("Generic_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Generic_Remove {
            get {
                return ResourceManager.GetString("Generic_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string Generic_Replacement_Empty {
            get {
                return ResourceManager.GetString("Generic_Replacement_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Generic_Reset {
            get {
                return ResourceManager.GetString("Generic_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root item.
        /// </summary>
        internal static string Generic_RootElement {
            get {
                return ResourceManager.GetString("Generic_RootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root items.
        /// </summary>
        internal static string Generic_RootElements {
            get {
                return ResourceManager.GetString("Generic_RootElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Generic_Search {
            get {
                return ResourceManager.GetString("Generic_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        internal static string Generic_SearchHits {
            get {
                return ResourceManager.GetString("Generic_SearchHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Generic_Success {
            get {
                return ResourceManager.GetString("Generic_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string Generic_Template {
            get {
                return ResourceManager.GetString("Generic_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Generic_Type {
            get {
                return ResourceManager.GetString("Generic_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Generic_Value {
            get {
                return ResourceManager.GetString("Generic_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string Generic_Values {
            get {
                return ResourceManager.GetString("Generic_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Generic_Version {
            get {
                return ResourceManager.GetString("Generic_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Generic_Warning {
            get {
                return ResourceManager.GetString("Generic_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select existing global macro to be attached.
        /// </summary>
        internal static string ItemHandlingSupport_AddExistingGlobalDefSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddExistingGlobalDefSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select existing template to be attached.
        /// </summary>
        internal static string ItemHandlingSupport_AddExistingTemplateSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddExistingTemplateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add global macro.
        /// </summary>
        internal static string ItemHandlingSupport_AddGlobalDef {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddGlobalDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option how to add the global macro.
        /// </summary>
        internal static string ItemHandlingSupport_AddGlobalDefOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddGlobalDefOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parameter used forglobal macro adding.
        /// </summary>
        internal static string ItemHandlingSupport_AddGlobalDefParameterSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddGlobalDefParameterSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add template.
        /// </summary>
        internal static string ItemHandlingSupport_AddTemplate {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option how to add the template.
        /// </summary>
        internal static string ItemHandlingSupport_AddTemplateOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddTemplateOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parameter used for template adding.
        /// </summary>
        internal static string ItemHandlingSupport_AddTemplateParameterSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddTemplateParameterSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to File Definition.
        /// </summary>
        internal static string ItemHandlingSupport_AddToFileDefinition {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddToFileDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select add to file definition option.
        /// </summary>
        internal static string ItemHandlingSupport_AddToFileDefinitionOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddToFileDefinitionOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to GlobalDef Definition.
        /// </summary>
        internal static string ItemHandlingSupport_AddToGlobalDefDefinition {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddToGlobalDefDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select add to GlobalDef definition option.
        /// </summary>
        internal static string ItemHandlingSupport_AddToGlobalDefDefinitionOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddToGlobalDefDefinitionOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to template definition.
        /// </summary>
        internal static string ItemHandlingSupport_AddToTemplateDefinition {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddToTemplateDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select add to template definition option.
        /// </summary>
        internal static string ItemHandlingSupport_AddToTemplateDefinitionOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_AddToTemplateDefinitionOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select existing global macro to be copied.
        /// </summary>
        internal static string ItemHandlingSupport_CreateFromCopyGlobalDefSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_CreateFromCopyGlobalDefSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select existing template to be copied.
        /// </summary>
        internal static string ItemHandlingSupport_CreateFromCopyTemplateSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_CreateFromCopyTemplateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List block using block groups.
        /// </summary>
        internal static string ItemHandlingSupport_ListBlockUsingBlockGroups {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListBlockUsingBlockGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List global macro users.
        /// </summary>
        internal static string ItemHandlingSupport_ListGlobalDefUsers {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListGlobalDefUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List inherited global macros.
        /// </summary>
        internal static string ItemHandlingSupport_ListInheritedGlobalDefs {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListInheritedGlobalDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List item using templates.
        /// </summary>
        internal static string ItemHandlingSupport_ListItemUsingTemplates {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListItemUsingTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List parameter using items.
        /// </summary>
        internal static string ItemHandlingSupport_ListParameterUsers {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListParameterUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List template users.
        /// </summary>
        internal static string ItemHandlingSupport_ListTemplateUsers {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListTemplateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List value using items.
        /// </summary>
        internal static string ItemHandlingSupport_ListValueUsers {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ListValueUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Handling Suppport.
        /// </summary>
        internal static string ItemHandlingSupport_MenuStripItem {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_MenuStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove global macro.
        /// </summary>
        internal static string ItemHandlingSupport_RemoveGlobalDef {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_RemoveGlobalDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option how to remove the global macro.
        /// </summary>
        internal static string ItemHandlingSupport_RemoveGlobalDefOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_RemoveGlobalDefOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove template.
        /// </summary>
        internal static string ItemHandlingSupport_RemoveTemplate {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_RemoveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option how to remove the template.
        /// </summary>
        internal static string ItemHandlingSupport_RemoveTemplateOptionSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_RemoveTemplateOptionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show linked template.
        /// </summary>
        internal static string ItemHandlingSupport_ShowLinkedTemplate {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_ShowLinkedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target global macro file.
        /// </summary>
        internal static string ItemHandlingSupport_TargetGlobalDefFileSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_TargetGlobalDefFileSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target template file.
        /// </summary>
        internal static string ItemHandlingSupport_TargetTemplateFileSelector {
            get {
                return ResourceManager.GetString("ItemHandlingSupport_TargetTemplateFileSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow fallback to original data.
        /// </summary>
        internal static string SettingsDialog_Creation_AllowFallbackToParsedData {
            get {
                return ResourceManager.GetString("SettingsDialog_Creation_AllowFallbackToParsedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Creation.
        /// </summary>
        internal static string SettingsDialog_Creation_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_Creation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate parent of invalid item.
        /// </summary>
        internal static string SettingsDialog_Creation_InvalidateParentOnError {
            get {
                return ResourceManager.GetString("SettingsDialog_Creation_InvalidateParentOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write only valid items to file.
        /// </summary>
        internal static string SettingsDialog_Creation_WriteOnlyValidItems {
            get {
                return ResourceManager.GetString("SettingsDialog_Creation_WriteOnlyValidItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        internal static string SettingsDialog_Filter_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_Filter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view &apos;comments&apos; initially visible.
        /// </summary>
        internal static string SettingsDialog_Filter_TreeViewFilterCommentsInitActive {
            get {
                return ResourceManager.GetString("SettingsDialog_Filter_TreeViewFilterCommentsInitActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view &apos;data blocks&apos; initially visible.
        /// </summary>
        internal static string SettingsDialog_Filter_TreeViewFilterDataBlocksInitActive {
            get {
                return ResourceManager.GetString("SettingsDialog_Filter_TreeViewFilterDataBlocksInitActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view &apos;parameters&apos; initially visible.
        /// </summary>
        internal static string SettingsDialog_Filter_TreeViewFilterParametersInitActive {
            get {
                return ResourceManager.GetString("SettingsDialog_Filter_TreeViewFilterParametersInitActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game version.
        /// </summary>
        internal static string SettingsDialog_General_GameMode {
            get {
                return ResourceManager.GetString("SettingsDialog_General_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsDialog_General_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsDialog_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string SettingsDialog_Info_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build block groups (BlockGroupsConfig).
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_BlockGroupsConfig_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_BlockGroupsConfig_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Has Value&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefHasValue {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Info&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefInfo {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Allowing Blank&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefIsAllowingBlank {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefIsAllowingBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Force Escaped&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefIsForceEscaped {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefIsForceEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Optional&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefIsOptional {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_FileParam_DefIsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Default Value &apos;Has Value&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefHasValue {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Default Value &apos;Info&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefInfo {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Default Value &apos;Is Allowing Blank&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsAllowingBlank {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsAllowingBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Default Value &apos;Is Force Escaped&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsForceEscaped {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsForceEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Default Value &apos;Is Optional&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsOptional {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Has Value&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefHasValue {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Info&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefInfo {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Allowing Blank&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefIsAllowingBlank {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefIsAllowingBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Force Escaped&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefIsForceEscaped {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefIsForceEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Optional&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefIsOptional {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_GlobalDefParam_DefIsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Has Value&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefHasValue {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Info&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefInfo {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Allowing Blank&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefIsAllowingBlank {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefIsAllowingBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Force Escaped&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefIsForceEscaped {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefIsForceEscaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Default Value &apos;Is Optional&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefIsOptional {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_DefVal_Ingredient_DefIsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Parameter.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_FileParamConfig_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_FileParamConfig_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_General_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global macros (GlobalDefsConfig).
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_GlobalDefConfig_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_GlobalDefConfig_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Handling Support.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter file checks active.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_InterFileChecksActive {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_InterFileChecksActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Key &apos;Blocks&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_ParamKey_Blocks {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_ParamKey_Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Key &apos;Template Root&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_ParamKey_TemplateRoot {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_ParamKey_TemplateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Keys &apos;GlobalRef&apos;.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_ParamKeys_GlobalRef {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_ParamKeys_GlobalRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates and ingredients.
        /// </summary>
        internal static string SettingsDialog_ItemHandlingSupport_TemplatesConfig_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_ItemHandlingSupport_TemplatesConfig_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error view item count preset.
        /// </summary>
        internal static string SettingsDialog_Sorter_ErrorViewSorterInitCount {
            get {
                return ResourceManager.GetString("SettingsDialog_Sorter_ErrorViewSorterInitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string SettingsDialog_Sorter_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_Sorter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter view item count preset.
        /// </summary>
        internal static string SettingsDialog_Sorter_ParameterViewSorterInitCount {
            get {
                return ResourceManager.GetString("SettingsDialog_Sorter_ParameterViewSorterInitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree view item count preset.
        /// </summary>
        internal static string SettingsDialog_Sorter_TreeViewSorterInitCount {
            get {
                return ResourceManager.GetString("SettingsDialog_Sorter_TreeViewSorterInitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value &apos;Unlock Cost&apos;.
        /// </summary>
        internal static string SettingsDialog_TechTree_DefVal_UnlockCost {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_DefVal_UnlockCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value &apos;Unlock Level&apos;.
        /// </summary>
        internal static string SettingsDialog_TechTree_DefVal_UnlockLevel {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_DefVal_UnlockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Tree.
        /// </summary>
        internal static string SettingsDialog_TechTree_Header {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Key &apos;Tech Tree Names&apos;.
        /// </summary>
        internal static string SettingsDialog_TechTree_ParamKey_TechTreeNames {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_ParamKey_TechTreeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Key &apos;Tech Tree Parent Name&apos;.
        /// </summary>
        internal static string SettingsDialog_TechTree_ParamKey_TechTreeParentName {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_ParamKey_TechTreeParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Key &apos;Unlock Cost&apos;.
        /// </summary>
        internal static string SettingsDialog_TechTree_ParamKey_UnlockCost {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_ParamKey_UnlockCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Key &apos;Unlock Level&apos;.
        /// </summary>
        internal static string SettingsDialog_TechTree_ParamKey_UnlockLevel {
            get {
                return ResourceManager.GetString("SettingsDialog_TechTree_ParamKey_UnlockLevel", resourceCulture);
            }
        }
    }
}
