//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int EgsEcfControls_TreeViewSorterInitCount {
            get {
                return ((int)(this["EgsEcfControls_TreeViewSorterInitCount"]));
            }
            set {
                this["EgsEcfControls_TreeViewSorterInitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int EgsEcfControls_ParameterViewSorterInitCount {
            get {
                return ((int)(this["EgsEcfControls_ParameterViewSorterInitCount"]));
            }
            set {
                this["EgsEcfControls_ParameterViewSorterInitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EgsEcfControls_ErrorViewSorterInitCount {
            get {
                return ((int)(this["EgsEcfControls_ErrorViewSorterInitCount"]));
            }
            set {
                this["EgsEcfControls_ErrorViewSorterInitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EgsEcfEditorApp_FileCreation_InvalidateParentsOnError {
            get {
                return ((bool)(this["EgsEcfEditorApp_FileCreation_InvalidateParentsOnError"]));
            }
            set {
                this["EgsEcfEditorApp_FileCreation_InvalidateParentsOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfEditorApp_FileCreation_WriteOnlyValidItems {
            get {
                return ((bool)(this["EgsEcfEditorApp_FileCreation_WriteOnlyValidItems"]));
            }
            set {
                this["EgsEcfEditorApp_FileCreation_WriteOnlyValidItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfControls_TreeViewFilterCommentsInitActive {
            get {
                return ((bool)(this["EgsEcfControls_TreeViewFilterCommentsInitActive"]));
            }
            set {
                this["EgsEcfControls_TreeViewFilterCommentsInitActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfControls_TreeViewFilterParametersInitActive {
            get {
                return ((bool)(this["EgsEcfControls_TreeViewFilterParametersInitActive"]));
            }
            set {
                this["EgsEcfControls_TreeViewFilterParametersInitActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfControls_TreeViewFilterDataBlocksInitActive {
            get {
                return ((bool)(this["EgsEcfControls_TreeViewFilterDataBlocksInitActive"]));
            }
            set {
                this["EgsEcfControls_TreeViewFilterDataBlocksInitActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vanilla")]
        public string EgsEcfEditorApp_ActiveGameMode {
            get {
                return ((string)(this["EgsEcfEditorApp_ActiveGameMode"]));
            }
            set {
                this["EgsEcfEditorApp_ActiveGameMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfEditorApp_FileCreation_AllowFallbackToParsedData {
            get {
                return ((bool)(this["EgsEcfEditorApp_FileCreation_AllowFallbackToParsedData"]));
            }
            set {
                this["EgsEcfEditorApp_FileCreation_AllowFallbackToParsedData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnlockLevel")]
        public string EcfTechTreeDialog_ParamKey_UnlockLevel {
            get {
                return ((string)(this["EcfTechTreeDialog_ParamKey_UnlockLevel"]));
            }
            set {
                this["EcfTechTreeDialog_ParamKey_UnlockLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnlockCost")]
        public string EcfTechTreeDialog_ParamKey_UnlockCost {
            get {
                return ((string)(this["EcfTechTreeDialog_ParamKey_UnlockCost"]));
            }
            set {
                this["EcfTechTreeDialog_ParamKey_UnlockCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TechTreeNames")]
        public string EcfTechTreeDialog_ParamKey_TechTreeNames {
            get {
                return ((string)(this["EcfTechTreeDialog_ParamKey_TechTreeNames"]));
            }
            set {
                this["EcfTechTreeDialog_ParamKey_TechTreeNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TechTreeParent")]
        public string EcfTechTreeDialog_ParamKey_TechTreeParentName {
            get {
                return ((string)(this["EcfTechTreeDialog_ParamKey_TechTreeParentName"]));
            }
            set {
                this["EcfTechTreeDialog_ParamKey_TechTreeParentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EcfTechTreeDialog_DefVal_UnlockLevel {
            get {
                return ((int)(this["EcfTechTreeDialog_DefVal_UnlockLevel"]));
            }
            set {
                this["EcfTechTreeDialog_DefVal_UnlockLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EcfTechTreeDialog_DefVal_UnlockCost {
            get {
                return ((int)(this["EcfTechTreeDialog_DefVal_UnlockCost"]));
            }
            set {
                this["EcfTechTreeDialog_DefVal_UnlockCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemplateRoot")]
        public string ItemHandlingSupport_ParamKey_TemplateName {
            get {
                return ((string)(this["ItemHandlingSupport_ParamKey_TemplateName"]));
            }
            set {
                this["ItemHandlingSupport_ParamKey_TemplateName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_Ingredient_DefIsOptional {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_Ingredient_DefIsOptional"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_Ingredient_DefIsOptional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_Ingredient_DefHasValue {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_Ingredient_DefHasValue"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_Ingredient_DefHasValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemHandlingSupport_DefVal_Ingredient_DefIsAllowingBlank {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_Ingredient_DefIsAllowingBlank"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_Ingredient_DefIsAllowingBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemHandlingSupport_DefVal_Ingredient_DefIsForceEscaped {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_Ingredient_DefIsForceEscaped"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_Ingredient_DefIsForceEscaped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tool-Added")]
        public string ItemHandlingSupport_DefVal_Ingredient_DefInfo {
            get {
                return ((string)(this["ItemHandlingSupport_DefVal_Ingredient_DefInfo"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_Ingredient_DefInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blocks")]
        public string ItemHandlingSupport_ParamKey_Blocks {
            get {
                return ((string)(this["ItemHandlingSupport_ParamKey_Blocks"]));
            }
            set {
                this["ItemHandlingSupport_ParamKey_Blocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_InterFileChecksActive {
            get {
                return ((bool)(this["ItemHandlingSupport_InterFileChecksActive"]));
            }
            set {
                this["ItemHandlingSupport_InterFileChecksActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_GlobalDefParam_DefIsOptional {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefParam_DefIsOptional"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefParam_DefIsOptional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_GlobalDefParam_DefHasValue {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefParam_DefHasValue"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefParam_DefHasValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_GlobalDefParam_DefIsAllowingBlank {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefParam_DefIsAllowingBlank"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefParam_DefIsAllowingBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_GlobalDefParam_DefIsForceEscaped {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefParam_DefIsForceEscaped"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefParam_DefIsForceEscaped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tool-Added")]
        public string ItemHandlingSupport_DefVal_GlobalDefParam_DefInfo {
            get {
                return ((string)(this["ItemHandlingSupport_DefVal_GlobalDefParam_DefInfo"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefParam_DefInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsOptional {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsOptional"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsOptional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_GlobalDefAttr_DefHasValue {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefHasValue"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefHasValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsAllowingBlank {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsAllowingBlank"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsAllowingBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsForceEscaped {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsForceEscaped"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefIsForceEscaped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tool-Added")]
        public string ItemHandlingSupport_DefVal_GlobalDefAttr_DefInfo {
            get {
                return ((string)(this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefInfo"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_GlobalDefAttr_DefInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GlobalRef,GlobalRef_1,GlobalRef_2,GlobalRef_3,GlobalRef_4,GlobalRef_5")]
        public string ItemHandlingSupport_ParamKeys_GlobalRef {
            get {
                return ((string)(this["ItemHandlingSupport_ParamKeys_GlobalRef"]));
            }
            set {
                this["ItemHandlingSupport_ParamKeys_GlobalRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_FileParam_DefIsOptional {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_FileParam_DefIsOptional"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_FileParam_DefIsOptional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemHandlingSupport_DefVal_FileParam_DefHasValue {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_FileParam_DefHasValue"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_FileParam_DefHasValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemHandlingSupport_DefVal_FileParam_DefIsAllowingBlank {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_FileParam_DefIsAllowingBlank"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_FileParam_DefIsAllowingBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemHandlingSupport_DefVal_FileParam_DefIsForceEscaped {
            get {
                return ((bool)(this["ItemHandlingSupport_DefVal_FileParam_DefIsForceEscaped"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_FileParam_DefIsForceEscaped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tool-Added")]
        public string ItemHandlingSupport_DefVal_FileParam_DefInfo {
            get {
                return ((string)(this["ItemHandlingSupport_DefVal_FileParam_DefInfo"]));
            }
            set {
                this["ItemHandlingSupport_DefVal_FileParam_DefInfo"] = value;
            }
        }
    }
}
