//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int EgsEcfControls_TreeViewSorterInitCount {
            get {
                return ((int)(this["EgsEcfControls_TreeViewSorterInitCount"]));
            }
            set {
                this["EgsEcfControls_TreeViewSorterInitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int EgsEcfControls_ParameterViewSorterInitCount {
            get {
                return ((int)(this["EgsEcfControls_ParameterViewSorterInitCount"]));
            }
            set {
                this["EgsEcfControls_ParameterViewSorterInitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EgsEcfControls_ErrorViewSorterInitCount {
            get {
                return ((int)(this["EgsEcfControls_ErrorViewSorterInitCount"]));
            }
            set {
                this["EgsEcfControls_ErrorViewSorterInitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EgsEcfEditorApp_InvalidateParentsOnError {
            get {
                return ((bool)(this["EgsEcfEditorApp_InvalidateParentsOnError"]));
            }
            set {
                this["EgsEcfEditorApp_InvalidateParentsOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfEditorApp_WriteOnlyValidItems {
            get {
                return ((bool)(this["EgsEcfEditorApp_WriteOnlyValidItems"]));
            }
            set {
                this["EgsEcfEditorApp_WriteOnlyValidItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfControls_TreeViewFilterCommentsInitActive {
            get {
                return ((bool)(this["EgsEcfControls_TreeViewFilterCommentsInitActive"]));
            }
            set {
                this["EgsEcfControls_TreeViewFilterCommentsInitActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfControls_TreeViewFilterParametersInitActive {
            get {
                return ((bool)(this["EgsEcfControls_TreeViewFilterParametersInitActive"]));
            }
            set {
                this["EgsEcfControls_TreeViewFilterParametersInitActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EgsEcfControls_TreeViewFilterDataBlocksInitActive {
            get {
                return ((bool)(this["EgsEcfControls_TreeViewFilterDataBlocksInitActive"]));
            }
            set {
                this["EgsEcfControls_TreeViewFilterDataBlocksInitActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vanilla")]
        public string EgsEcfEditorApp_ActiveGameVersion {
            get {
                return ((string)(this["EgsEcfEditorApp_ActiveGameVersion"]));
            }
            set {
                this["EgsEcfEditorApp_ActiveGameVersion"] = value;
            }
        }
    }
}
