//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgsEcfEditorApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class WindowSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WindowSettings defaultInstance = ((WindowSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowSettings())));
        
        public static WindowSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int EgsEcfControls_TreeViewInitWidth {
            get {
                return ((int)(this["EgsEcfControls_TreeViewInitWidth"]));
            }
            set {
                this["EgsEcfControls_TreeViewInitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int EgsEcfControls_InfoViewInitWidth {
            get {
                return ((int)(this["EgsEcfControls_InfoViewInitWidth"]));
            }
            set {
                this["EgsEcfControls_InfoViewInitWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int EgsEcfControls_ErrorViewInitHeight {
            get {
                return ((int)(this["EgsEcfControls_ErrorViewInitHeight"]));
            }
            set {
                this["EgsEcfControls_ErrorViewInitHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int EgsEcfEditorApp_Width {
            get {
                return ((int)(this["EgsEcfEditorApp_Width"]));
            }
            set {
                this["EgsEcfEditorApp_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int EgsEcfEditorApp_Height {
            get {
                return ((int)(this["EgsEcfEditorApp_Height"]));
            }
            set {
                this["EgsEcfEditorApp_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int EgsEcfEditorApp_X {
            get {
                return ((int)(this["EgsEcfEditorApp_X"]));
            }
            set {
                this["EgsEcfEditorApp_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int EgsEcfEditorApp_Y {
            get {
                return ((int)(this["EgsEcfEditorApp_Y"]));
            }
            set {
                this["EgsEcfEditorApp_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string EgsEcfEditorApp_WindowState {
            get {
                return ((string)(this["EgsEcfEditorApp_WindowState"]));
            }
            set {
                this["EgsEcfEditorApp_WindowState"] = value;
            }
        }
    }
}
